### ISSUE TITLE
Brian2 update breaks statemonitor

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#165]
Relevant changes are in PR #164. I merged and then reverted the merge (so changes from the PR are not applied even though PR is closed!).

The issue is in the `{# WRITES_TO_READ_ONLY_VARIABLES { t, N } #}` of the statemonitor. With that line this minimal example

```python
from brian2 import *
import brian2cuda

set_device('cuda_standalone')

G = NeuronGroup(1, '''dv/dt = -v/ms : 1''')
mon = StateMonitor(G, [], record=True)

run(1*ms)
```

gives

```
Traceback (most recent call last):
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/groups/group.py", line 1128, in before_run
    codeobj_class=self.codeobj_class
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/codegen/codeobject.py", line 310, in create_runner_codeobj
    override_conditional_write=override_conditional_write,
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/brian2cuda/device.py", line 331, in code_object
    override_conditional_write=override_conditional_write,
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/devices/cpp_standalone/device.py", line 578, in code_object
    for varname in template.writes_read_only}
  File "/home/denis/projects/brian2cuda/brian2cuda_repository/frozen_repos/brian2/brian2/devices/cpp_standalone/device.py", line 578, in <setcomp>
    for varname in template.writes_read_only}
KeyError: u'N'

Error encountered with object named "statemonitor".
Object was created here (most recent call only, full details in debug log):
  File "test.py", line 12, in <module>
    mon = StateMonitor(G, [], record=True)

An error occurred when preparing an object. KeyError: u'N'
```

Looks like the `N` variable is not present in the statemonitor codeobject?

Should be fixed with the other statemonitor problems (#50), that template is a mess which I didn't get around fixing yet...

@mstimberg do you see directly what the problem is? Otherwise Ill look into it when I do the statemonitor.

**Comment by mstimberg** [comment]
> Looks like the `N` variable is not present in the statemonitor codeobject?

Ah, right, sorry about that, I couldn't properly test the changes back at the time. I think the fix is simply to include it `N` in the `USES_VARIABLES` template comment. I can prepare a new PR if you want?

**Comment by denisalevi** [comment]
Finally added that little `N`. Thanks for the quick fix! :)
