### ISSUE TITLE
New brian2cuda gpu detection test fails when run as part of test sutie

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#196]
Two new tests I wrote for GPU selection fail during compilation, but only when run as part of the test suite. When running them as single tests or when running just all tests in the `test_gpu_selection.py` file, everything passes fine (both locally and on the cluster).

Don't really know how to debug this, captured stdout is not helpful. I will leave this for now and revisit once we updated the brian2 version, which also includes moving from `nosetest` to `pytest`.

These are the tests, that fail:
- [test_manual_setting_compute_capability.py](https://github.com/brian-team/brian2cuda/blob/4007b84d9176f3842863b50779f7e106319e0693/brian2cuda/tests/test_gpu_detection.py#L24-L36)
- [test_warning_compute_capability_set_twice.py](https://github.com/brian-team/brian2cuda/blob/4007b84d9176f3842863b50779f7e106319e0693/brian2cuda/tests/test_gpu_detection.py#L45-L51)

These are the test suite logs:
```
ERROR: brian2cuda.tests.test_gpu_detection.test_manual_setting_compute_capability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cognition/home/denis/anaconda3/envs/b2c/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/tests/test_gpu_detection.py", line 45, in test_manual_setting_compute_capability
    run(0*ms)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/base.py", line 274, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/device.py", line 1412, in network_run
    self.build(direct_call=False, **self.build_options)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/device.py", line 1211, in build
    self.compile_source(directory, cpp_compiler, debug, clean)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/devices/cpp_standalone/device.py", line 960, in compile_source
    raise RuntimeError(error_message)
RuntimeError: Project compilation failed (error code: 512). Consider running with "clean=True" to force a complete rebuild.
-------------------- >> begin captured stdout << ---------------------
makefile:22: recipe for target 'executable' failed

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: brian2cuda.tests.test_gpu_detection.test_warning_compute_capability_set_twice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cognition/home/denis/anaconda3/envs/b2c/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/tests/test_gpu_detection.py", line 67, in test_warning_compute_capability_set_twice
    run(0*ms)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/core/base.py", line 274, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/device.py", line 1412, in network_run
    self.build(direct_call=False, **self.build_options)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/brian2cuda/device.py", line 1211, in build
    self.compile_source(directory, cpp_compiler, debug, clean)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-01_14:00:45_stash-summed-array-fix-after-ANOTHER-master-merge/frozen_repos/brian2/brian2/devices/cpp_standalone/device.py", line 960, in compile_source
    raise RuntimeError(error_message)
RuntimeError: Project compilation failed (error code: 512). Consider running with "clean=True" to force a complete rebuild.
-------------------- >> begin captured stdout << ---------------------
makefile:22: recipe for target 'executable' failed
makefile:22: recipe for target 'executable' failed

--------------------- >> end captured stdout << ----------------------
```

**Comment by denisalevi** [comment]
Added two new tests and one of them fails when run in the test suite and not when run as script (see 07a417d).

**Comment by denisalevi** [comment]
After adding fixtures to correctly setup/teardown CUDA installation and GPU selection detection between tests, all tests in `test_gpu_detection.py` are passing.
Happened in PR #229
