### ISSUE TITLE
Test failing: `test_user_defined_function` is failing

### ISSUE THREAD

**Issue by denisalevi** [brian-team/brian2cuda#203]
I think this test used to pass at some point. Seems to be a problem in the `statemonitor`. Maybe fix when doing #201.

```
NOT_IMPLEMENTED: brian2.tests.test_functions.test_user_defined_function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cognition/home/denis/anaconda3/envs/b2c/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/tests/test_functions.py", line 194, in test_user_defined_function
    run(default_dt)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/units/fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/magic.py", line 371, in run
    namespace=namespace, profile=profile, level=2+level)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/magic.py", line 231, in run
    namespace=namespace, profile=profile, level=level+1)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/base.py", line 274, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/brian2cuda/device.py", line 1235, in network_run
    net.before_run(namespace)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/base.py", line 276, in device_override_decorated_function
    return func(*args, **kwds)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/network.py", line 843, in before_run
    raise brian_object_exception("An error occurred when preparing an object.", obj, ex)
BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/core/network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/groups/group.py", line 1128, in before_run
    codeobj_class=self.codeobj_class
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/codegen/codeobject.py", line 310, in create_runner_codeobj
    override_conditional_write=override_conditional_write,
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/brian2cuda/device.py", line 451, in code_object
    override_conditional_write=override_conditional_write,
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/devices/cpp_standalone/device.py", line 565, in code_object
    override_conditional_write=override_conditional_write,
  File "/cognition/home/denis/projects/brian2cuda/test-suite/brian2cuda-synced-repos/21-04-14_14:10:05_fix-monitor-indexing/frozen_repos/brian2/brian2/devices/device.py", line 302, in code_object
    '%s: %s') % (varname, ex))
NotImplementedError: Cannot use function usersin: 'No implementation available for target cuda. Available implementations: cpp, cython'

Error encountered with object named "statemonitor".
Object was created here (most recent call only, full details in debug log):
  File "/cognition/home/denis/anaconda3/envs/b2c/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)

An error occurred when preparing an object. NotImplementedError: Cannot use function usersin: 'No implementation available for target cuda. Available implementations: cpp, cython'
(See above for original error message and traceback.)
```

**Comment by denisalevi** [comment]
Ahh... nevermind. It's just a `NotImplementedError`. Since all other `NotImplementedError`s we had were due to bugs, I thought its an actual error, but it isn't. We have a `cuda_standalone` version of this test and it is passing. I will disable that the test suite fails on `NotImplementedError`s now.
