### ISSUE TITLE
Needs patch to run with Brian 2.4.2

### ISSUE THREAD

**Issue by mstimberg** [brian-team/brian2cuda#276]
I just realized that a small change in the `brian2.diff` is actually necessary to run simulations with Brian 2.4.2, i.e. not only to run the profiling/benchmarks.

Running without the patch fails with
```pytb
Traceback (most recent call last):
  File "/home/marcel/programming/brian2cuda/examples/stdp.py", line 169, in <module>
    run(100*second, report='text', profile=params['profiling'])
  File "/home/marcel/programming/brian2/brian2/units/fundamentalunits.py", line 2434, in new_f
    result = f(*args, **kwds)
  File "/home/marcel/programming/brian2/brian2/core/magic.py", line 373, in run
    return magic_network.run(duration, report=report, report_period=report_period,
  File "/home/marcel/programming/brian2/brian2/core/magic.py", line 231, in run
    Network.run(self, duration, report=report, report_period=report_period,
  File "/home/marcel/programming/brian2/brian2/core/base.py", line 276, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File "/home/marcel/programming/brian2cuda/brian2cuda/device.py", line 1560, in network_run
    run_lines.extend(self.code_lines['before_run'])
KeyError: 'before_run'
```
A quick fix that should work with patched and unpatched Brian is to add
```Python
        self.code_lines.update({'before_run': [],
                                'after_run': []})
```
here: https://github.com/brian-team/brian2cuda/blob/ae004be6b220c0d670f6ad8aca181d37a1c99654/brian2cuda/device.py#L76

**Comment by denisalevi** [comment]
I didn't try to get Brian2CUDA in it's current version to work with Brian2 2.4.2 without the patch. I wanted to update to Brian2 2.5 now and try to get rid of the patch file altogether in the process.

But if this is the only thing that stops Brian2CUDA to work with Brian2 2.4.2, then I'll happily add that, thanks :)
