### ISSUE TITLE
NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run.

### ISSUE THREAD

**Issue by emirhanbilgic** [brian-team/brian2cuda#317]
Hello! I am trying to implement the model described in Diehl's paper, "Unsupervised Learning of Digit Recognition Using Spike-Timing-Dependent Plasticity," and optimize its performance by running it on CUDA using the brian2cuda backend.

However, I encountered an error during execution. Specifically, the error occurs in a section of the code where divisive weight normalization is performed on synaptic weights. Below are the details of the code and error:

My simplified code: 

```
set_device("cuda_standalone", build_on_run=True)
 
device = get_device()
device.build_options.update({'clean': True})  
device.build_options.update({'debug': True})
```

...

```
# Create neuron groups for excitatory and inhibitory neurons
neuron_group_exc = brian2.NeuronGroup(N=population_exc, model=ng_eqs_exc, threshold=ng_threshold_exc, reset=ng_reset_exc, refractory=5*brian2.ms, method="euler")
neuron_group_inh = brian2.NeuronGroup(N=population_inh, model=ng_eqs_inh, threshold=ng_threshold_inh, reset=ng_reset_inh, refractory=2*brian2.ms, method="euler")

# Set initial values
neuron_group_exc.v = E_rest_exc - 40 * brian2.mV
neuron_group_inh.v = E_rest_inh - 40 * brian2.mV
neuron_group_exc.theta = 20 * brian2.mV

# Define PoissonGroup for input image (MNIST)
tot_input_num = size_selected * size_selected
image_input = brian2.PoissonGroup(N=tot_input_num, rates=0*brian2.Hz)  # Will set the rates based on the image

# Synapse connecting input neurons to excitatory neurons
syn_input_exc = brian2.Synapses(image_input, neuron_group_exc, model=syn_eqs_ee_training, on_pre=syn_on_pre_ee_training, on_post=syn_on_post_ee_training, method="euler")
syn_input_exc.connect()
syn_input_exc.w_ee[:] = "rand() * 0.3"
syn_input_exc.delay = 10 * brian2.ms

# Synapse connecting excitatory -> inhibitory neurons (one-to-one)
syn_exc_inh = brian2.Synapses(neuron_group_exc, neuron_group_inh, model="w_ei : 1", on_pre="g_e_post += w_ei", method="euler")
syn_exc_inh.connect(j='i')  # One-to-one connection
syn_exc_inh.w_ei = w_ei_

# Synapse connecting inhibitory -> excitatory neurons (all-to-all except same index)
syn_inh_exc = brian2.Synapses(neuron_group_inh, neuron_group_exc, model="w_ie : 1", on_pre="g_i_post += w_ie", method="euler")
syn_inh_exc.connect("i != j")
syn_inh_exc.w_ie = w_ie_

#weight_mon = StateMonitor(syn_input_exc, 'w_ee', record=False)
spike_mon_exc = brian2.SpikeMonitor(neuron_group_exc)
net = brian2.Network(neuron_group_exc, neuron_group_inh, image_input, syn_input_exc, syn_exc_inh, syn_inh_exc, spike_mon_exc)
image_input_rates, image_labels, image_intensities = functions_basic.get_spiking_rates_and_labels(use_test_data_mnist = False,
                                                                                  image_count=image_count,
                                                                                  seed_data=seed_train,
                                                                                  size_selected=size_selected,
                                                                                  start_index=start_index)
all_spike_counts_per_image = []
max_rate_current_image = max_rate
predicted_labels = []
image_labels_in_loop = []
cumulative_accuracies = []
image_indexes_in_loop = []
spike_data_within_training = []

with tqdm(total=image_count, desc="Processing Images", dynamic_ncols=True) as pbar:
    # Initialize spike counts for excitatory neurons
    previous_spike_counts = np.zeros(population_exc, dtype=int)
    
    # Loop through each image
    for image_index_in_loop in range(image_count):
        current_image_index = start_index + image_index_in_loop  # Absolute index of the current image
        tot_seen_images = image_index_in_loop + 1  # Total images processed so far
        image_retries = 0  # Retry counter for current image
        successful_training = False  # Flag to indicate whether training is successful
        
        # Retry until the image causes sufficient spiking activity
        while not successful_training:
            previous_spike_counts = spike_mon_exc.count[:]  # Record previous spike counts
            image_input.rates = image_input_rates[image_index_in_loop] * brian2.Hz  # Set input rates for the current image
            
            # Optional divisive weight normalization to keep weights in range
            if not skip_norm:
                functions_basic.divisive_weight_normalization(syn_input_exc, population_exc, normalization_value=normalization_val)
    
            # Run the simulation for a specified duration
            net.run(350 * brian2.ms)
```

I am having an error at this part, before running the simulation. The function I call from outside, which is not in this code, is this and it is quite simple: 

```
def divisive_weight_normalization(synapse, population_exc: int, normalization_value: float) -> None:

    for post_idx in range(population_exc):

        target_indices = np.where(synapse.j == post_idx)[0]
 
        weights_to_same_post = synapse.w_ee[target_indices]


        sum_of_weights = np.sum(weights_to_same_post)
        normalization_factor = normalization_value / sum_of_weights
```

The error: 

`NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run.`

All logs: 

```
pygame 2.6.1 (SDL 2.28.4, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO       CUDA installation directory detected via location of nvcc binary: /usr/local/cuda [brian2cuda.utils.gputools]
Processing Images:   0% 0/100 [00:00<?, ?it/s]
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_ws1mx17d.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_lov98a5l.py You can also include a copy of the redirected std stream outputs, available at '/tmp/brian_stdout_8dmzaqx3.log' and '/tmp/brian_stderr_4wzhke9s.log'. Thanks! [brian2]
Traceback (most recent call last):
  File "/content/cuda_snn/train_only.py", line 188, in <module>
    functions_basic.divisive_weight_normalization(syn_input_exc, population_exc, normalization_value=normalization_val)
  File "/content/cuda_snn/functions_basic.py", line 111, in divisive_weight_normalization
    target_indices = np.where(synapse.j == post_idx)[0]
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/variables.py", line 1532, in __eq__
    return self.get_item(slice(None), level=1) == np.asanyarray(other)
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/variables.py", line 915, in get_item
    values = self.get_with_index_array(item)
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/base.py", line 346, in device_override_decorated_function
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/variables.py", line 1239, in get_with_index_array
    return variable.get_value()[indices]
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/variables.py", line 517, in get_value
    return self.device.get_value(self)
  File "/usr/local/lib/python3.10/dist-packages/brian2/devices/cpp_standalone/device.py", line 577, in get_value
    raise NotImplementedError(
NotImplementedError: Cannot retrieve the values of state variables in standalone code before the simulation has been run.
Exception ignored in: <function BrianObject.__del__ at 0x784c81b96950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/base.py", line 190, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
Exception ignored in: <function BrianObject.__del__ at 0x784c81b96950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/base.py", line 190, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
Exception ignored in: <function BrianObject.__del__ at 0x784c81b96950>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/brian2/core/base.py", line 190, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'

```

Thank you! The all code is here: https://github.com/emirhanbilgic/cuda_snn

**Comment by denisalevi** [comment]
Hi,

for Brian usage questions, please use the [Discourse forum](https://brian.discourse.group/) in the future and keep this GitHub issue tracker for bug reports.

Your issue is not related to Brian2CUDA but is a limitation of Brian's standalone code generation mode (you will get the same error with the `"cpp_standalone"` device). Your error is happening in the line
```python
target_indices = np.where(synapse.j == post_idx)[0]
```
You are trying to access synapse indices but since the synapses are not generated yet (which will only happen once you call `run`), you see the error that you are seeing. You might be able to circumvent the problem by using string expressions, see e.g. [here in the docs](https://brian2.readthedocs.io/en/stable/user/computation.html#variables). For further help on that, please ask in the Discord forum.
